
# objectives:
#   objective_library_paths:
#     example_objective:
#       package_name: "sinter_robot_mock"
#       relative_path: "objectives"



hardware:
  robot_description:
    urdf:
      package: "sinter_robot_mock"
      path: "urdf/j2n6s300.urdf.xacro"
    urdf_params:
      - hardware_interface: "mock"
    srdf:
      package: "sinter_robot_mock"
      path: "config/moveit/j2n300s.srdf"
  launch_control_node: true
  launch_robot_state_publisher: true
  simulated: false

ros_global_params:
  use_sim_time: False
  robot_description_timeout: 10.0

ros2_control:
  config:
    package: "sinter_robot_mock"
    path: "config/control/ros2_controllers.yaml"

  controllers_active_at_startup:
    - "joint_state_broadcaster"
    - "joint_trajectory_admittance_controller"
  controllers_inactive_at_startup:
    - "velocity_force_controller"
    - "joint_velocity_controller"

moveit_params:
  joint_group_name: "manipulator"
  kinematics:
    package: "sinter_robot_mock"
    path: "config/moveit/pose_ik.yaml"
  joint_limits:
    package: "sinter_robot_mock"
    path: "config/moveit/joint_limits.yaml"
  joint_jog:
    package: "sinter_robot_mock"
    path: "config/moveit/joint_jog.yaml"
  pose_jog:
    package: "sinter_robot_mock"
    path: "config/moveit/pose_jog.yaml"
  moveit_params:
  trajectory_execution:
    manage_controllers: true
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01
    control_multi_dof_joint_variables: false
  publish:
    planning_scene: true
    geometry_updates: true
    state_updates: true
    transforms_updates: true
# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Pro Behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_pro::behaviors::CoreBehaviorsLoader"
      - "moveit_pro::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_pro::behaviors::VisionBehaviorsLoader"
      - "moveit_pro::behaviors::MPCBehaviorsLoader"
      - "moveit_pro::behaviors::ConverterBehaviorsLoader"
      - "moveit_pro::behaviors::MujocoBehaviorsLoader"
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    core_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/core"
    motion_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/motion"
    perception_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/perception"
    mujoco_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/mujoco"
    visualization_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/visualization"
    sinter_objectives:
      package_name: "sinter_robot_mock"
      relative_path: "objectives"

  waypoints_file:
    package_name: "sinter_robot_mock"
    relative_path: "waypoints/waypoints.yaml"


# ###############################################################
# #
# #  This configures the robot to work with moveit pro
# #
# ###############################################################

# hardware:
#   # Set simulated to false if you are using this as a configuration for real hardware.
#   # This allows users to switch between mock and real hardware using the same configuration.
#   # [Required]
#   simulated: True

#   # If the MoveIt Pro Agent should launch the ros2 controller node.
#   # [Optional, default=True]
#   launch_control_node: True

#   # If the MoveIt Pro Agent should launch the robot state publisher.
#   # This should be false if you are launching the robot state publisher as part of drivers.
#   # [Optional, default=True]
#   launch_robot_state_publisher: True

#   # Specify additional launch files for running the robot with real hardware.
#   # [Optional, defaults to a blank launch file if not specified]
#   robot_driver_persist_launch_file:
#     package: "kinova_gen3_base_config"
#     path: "launch/robot_drivers_to_persist.launch.py"

#   # Specify any additional launch files for running the robot in simulation mode.
#   # Used when hardware.simulated is True.
#   # [Optional, defaults to a blank launch file if not specified]
#   simulated_robot_driver_persist_launch_file:
#     package: "kinova_gen3_base_config"
#     path: "launch/sim/robot_drivers_to_persist_sim.launch.py"
#   simulated_hardware_launch_file:
#     package: "moveit_studio_agent"
#     path: "launch/blank.launch.py"

#   # These Params are pasted to the XACRO to create the URDF
#   robot_description:
#     urdf:
#       package: "kinova_gen3_base_config"
#       path: "description/picknik_kinova_gen3.xacro"
#     srdf:
#       package: "kinova_gen3_base_config"
#       path: "config/moveit/picknik_kinova_gen3_base.srdf"
#     urdf_params:
#       - arm: "gen3"
#       - dof: "7"
#       - vision: "false"
#       - robot_ip: ""
#       - gripper: "robotiq_2f_85"
#       - username: "admin"
#       - password: "admin"
#       - port: "10000"
#       - port_realtime: "10001"
#       - session_inactivity_timeout_ms: "60000"
#       - connection_inactivity_timeout_ms: "2000"
#       - use_fake_hardware: "true"
#       - fake_sensor_commands: "false"
#       - external_camera: "true"
#       - wrist_realsense: "true"
#       - use_internal_bus_gripper_comm: "false"

# # This Configures moveit params that are in moveit_config.py
# moveit_params:
#   joint_group_name: "manipulator"

#   kinematics:
#     package: "kinova_gen3_base_config"
#     path: "config/moveit/pose_ik_distance.yaml"
#   sensors_3d:
#     package: "kinova_gen3_base_config"
#     path: "config/moveit/sensors_3d.yaml"
#   joint_limits:
#     package: "kinova_gen3_base_config"
#     path: "config/moveit/joint_limits.yaml"

#   publish:
#     planning_scene: True
#     geometry_updates: True
#     state_updates: True
#     transforms_updates: True

#   trajectory_execution:
#     manage_controllers: True
#     allowed_execution_duration_scaling: 2.0
#     allowed_goal_duration_margin: 5.0
#     allowed_start_tolerance: 0.01

# # This configures what controllers gets run at startup
# ros2_control:
#   config:
#     package: "kinova_gen3_base_config"
#     path: "config/control/picknik_kinova_gen3.ros2_control.yaml"
#   # Load and start these controllers so they can be used immediately.
#   controllers_active_at_startup:
#     - "robotiq_gripper_controller"
#     - "joint_state_broadcaster"
#     - "fault_controller"
#   controllers_inactive_at_startup:
#     - "joint_trajectory_controller"

# objectives:
#   behavior_loader_plugins:
#     # This plugin will load the core MoveIt Pro behaviors.
#     # Add additional plugin loaders as needed.
#     core:
#       - "moveit_pro::behaviors::CoreBehaviorsLoader"
#       - "moveit_pro::behaviors::MTCCoreBehaviorsLoader"
#       - "moveit_pro::behaviors::VisionBehaviorsLoader"
#       - "moveit_pro::behaviors::ConverterBehaviorsLoader"
#   objective_library_paths:
#     core_objectives:
#       package_name: "moveit_pro_objectives"
#       relative_path: "objectives/core"
#     motion_objectives:
#       package_name: "moveit_pro_objectives"
#       relative_path: "objectives/motion"
#     perception_objectives:
#       package_name: "moveit_pro_objectives"
#       relative_path: "objectives/perception"
#     sim_objectives:
#       package_name: "kinova_gen3_base_config"
#       relative_path: "objectives"
#   waypoints_file:
#     package_name: "kinova_gen3_base_config"
#     relative_path: "waypoints/waypoints.yaml"
