

hardware:
  robot_description:
    urdf:
      package: "sinter_robot_mock"
      path: "urdf/j2n6s300.urdf.xacro"
    urdf_params:
      - hardware_interface: "mock"
    srdf:
      package: "sinter_robot_mock"
      path: "config/moveit/j2n300s.srdf"
  launch_control_node: true
  launch_robot_state_publisher: true
  simulated: false

ros_global_params:
  use_sim_time: False
  robot_description_timeout: 10.0

ros2_control:
  config:
    package: "sinter_robot_mock"
    path: "config/control/ros2_controllers.yaml"

  controllers_active_at_startup:
    - "joint_state_broadcaster"
    - "joint_trajectory_admittance_controller"
    - "joint_velocity_controller"
  controllers_inactive_at_startup:
    - "velocity_force_controller"

moveit_params:
  joint_group_name: "manipulator"
  kinematics:
    package: "sinter_robot_mock"
    path: "config/moveit/pose_ik.yaml"
  joint_limits:
    package: "sinter_robot_mock"
    path: "config/moveit/joint_limits.yaml"
  joint_jog:
    package: "sinter_robot_mock"
    path: "config/moveit/joint_jog.yaml"
  pose_jog:
    package: "sinter_robot_mock"
    path: "config/moveit/pose_jog.yaml"
  moveit_params:
  trajectory_execution:
    manage_controllers: true
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01
    control_multi_dof_joint_variables: false
  publish:
    planning_scene: true
    geometry_updates: true
    state_updates: true
    transforms_updates: true
# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Pro Behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_pro::behaviors::CoreBehaviorsLoader"
      - "moveit_pro::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_pro::behaviors::VisionBehaviorsLoader"
      - "moveit_pro::behaviors::MPCBehaviorsLoader"
      - "moveit_pro::behaviors::ConverterBehaviorsLoader"
      - "moveit_pro::behaviors::MujocoBehaviorsLoader"
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    core_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/core"
    motion_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/motion"
    perception_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/perception"
    mujoco_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/mujoco"
    visualization_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/visualization"
    sinter_objectives:
      package_name: "sinter_robot_mock"
      relative_path: "objectives"

  waypoints_file:
    package_name: "sinter_robot_mock"
    relative_path: "waypoints/waypoints.yaml"